# permissions for end users to edit failovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multicluster-failover-operator
    app.kubernetes.io/managed-by: kustomize
  name: failover-editor-role
rules:
- apiGroups:
  - crd.hahomelabs.com
  resources:
  - failovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.hahomelabs.com
  resources:
  - failovers/status
  verbs:
  - get
