# permissions for end users to edit failovergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multicluster-failover-operator
    app.kubernetes.io/managed-by: kustomize
  name: failovergroup-editor-role
rules:
- apiGroups:
  - crd.hahomelabs.com
  resources:
  - failovergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.hahomelabs.com
  resources:
  - failovergroups/status
  verbs:
  - get
