---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.hahomelabs.com
  resources:
  - failovergroups
  - failovergroups/status
  - failovers
  - failovers/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.hahomelabs.com
  resources:
  - failovergroups/finalizers
  - failovers/finalizers
  verbs:
  - update
