apiVersion: v1
kind: Namespace
metadata:
  name: multicluster-failover-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multicluster-failover-operator-controller-manager
  namespace: multicluster-failover-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicluster-failover-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.hahomelabs.com
  resources:
  - failovers
  - failovergroups
  - failovers/status
  - failovergroups/status
  - failovers/finalizers
  - failovergroups/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicluster-failover-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-failover-operator-manager-role
subjects:
- kind: ServiceAccount
  name: multicluster-failover-operator-controller-manager
  namespace: multicluster-failover-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-failover-operator-controller-manager
  namespace: multicluster-failover-operator-system
  labels:
    app: multicluster-failover-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicluster-failover-operator
  template:
    metadata:
      labels:
        app: multicluster-failover-operator
    spec:
      serviceAccountName: multicluster-failover-operator-controller-manager
      containers:
      - name: manager
        image: hahomelabs/multicluster-failover-operator:latest
        imagePullPolicy: IfNotPresent
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10 