apiVersion: v1
kind: Secret
metadata:
  name: redis-config
  namespace: multicluster-failover-operator-system
type: Opaque
stringData:
  redis-hosts: "<host>,<host>,<host>"
  redis-port: "<port>"
  redis-password: "<password>"
  redis-db: "0"
  redis-leader-key: "multicluster:leader"