apiVersion: v1
kind: Secret
metadata:
  name: cluster1
  namespace: multicluster-failover-operator-system
  labels:
    sigs.k8s.io/multicluster-runtime-kubeconfig: "true"
type: Opaque
data:
  # Note: Replace this with your actual base64-encoded kubeconfig
  # You can generate this with: cat ~/.kube/config | base64 -w0
  kubeconfig: QkFTRTY0X0VORU9ERURfS1VCRUNPTkZJR19DT05URU5UU19HT19IRVJF
---
# Example using stringData which will be automatically encoded
apiVersion: v1
kind: Secret
metadata:
  name: remote-cluster-2
  namespace: multicluster-failover-operator-system
  labels:
    sigs.k8s.io/multicluster-runtime-kubeconfig: "true"
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: remote-cluster
      cluster:
        server: https://api.remote-cluster.example.com:6443
        certificate-authority-data: <REDACTED>
    contexts:
    - name: remote-cluster
      context:
        cluster: remote-cluster
        user: remote-cluster-admin
    current-context: remote-cluster
    users:
    - name: remote-cluster-admin
      user:
        client-certificate-data: <REDACTED>
        client-key-data: <REDACTED> 